name: Test toolchain

on:
  pull_request:
    paths:
      - ".github/workflows/bun-test.yaml"
      - "src/**"
      - "test/**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          bun-version: latest
      - uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1
      - run: bun install
      - run: bun test test/**
