name: Test toolchain

on:
  pull_request:
    paths:
      - ".github/workflows/bun-test.yaml"
      - "src/**"
      - "test/**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          bun-version: latest
      - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
      - run: bun install
      - run: bun test test/**
