name: Test toolchain

on:
  pull_request:
    paths:
      - ".github/workflows/bun-test.yaml"
      - "src/**"
      - "test/**"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          bun-version: latest
      - uses: oven-sh/setup-bun@123c6c4e2fea3eb7bffaa91a85eb6b3d505bf7af # v2
      - run: bun install
      - run: bun test test/**
